export const LOG_USER_IN_SUCCESS = 'LOG_USER_IN_SUCCESS';
export const LOG_USER_IN_LOADING = 'LOG_USER_IN_LOADING';
export const LOG_USER_IN_FAILURE = 'LOG_USER_IN_FAILURE';
export const LOG_USER_IN_FULFILL = 'LOG_USER_IN_FULFILL';

export const LOG_USER_OUT_SUCCESS = 'LOG_USER_OUT_SUCCESS';
export const LOG_USER_OUT_LOADING = 'LOG_USER_OUT_LOADING';
export const LOG_USER_OUT_FAILURE = 'LOG_USER_OUT_FAILURE';
export const LOG_USER_OUT_FULFILL = 'LOG_USER_OUT_FULFILL';
